version: '3.2'

services:
 
  web:
    build:
      context: './.docker/phpApache/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: php_web
    
    volumes:
      - ./site/:/var/www/site/
      - ./.docker/phpApache/vhost/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.docker/phpApache/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "${APACHE_HTTP_PORT}:80"
    stdin_open: true
    tty: true
